#ifndef CONTROLLER_MAP_H_
#define CONTROLLER_MAP_H_

#define CONTROLLER_LENGTH 3

#define ANALOG_CONTROLLER 0
#define DIGITAL_CONTROLLER 1

static const int controller_map[CONTROLLER_LENGTH] = {
	DIGITAL_CONTROLLER,
	ANALOG_CONTROLLER,
	ANALOG_CONTROLLER
};



#endif /* CONTROLLER_MAP_H_ */